'use client'

import * as React from 'react'
import { CKEditor } from '@ckeditor/ckeditor5-react'
import {
  ClassicEditor,
  Autosave,
  Essentials,
  Paragraph,
  Alignment,
  AutoImage,
  Autoformat,
  AutoLink,
  Base64UploadAdapter,
  ImageBlock,
  BlockQuote,
  Bold,
  CloudServices,
  Code,
  CodeBlock,
  Emoji,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  ImageCaption,
  ImageInsertViaUrl,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  ImageInline,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  MediaEmbed,
  Mention,
  PasteFromMarkdownExperimental,
  PlainTableOutput,
  ShowBlocks,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableToolbar,
  TextTransformation,
  Underline,
  SourceEditing,
  ImageResize,
  TableCellProperties,
  TableProperties,
  TableColumnResize,
  HtmlEmbed,
  Style,
  AutoMediaEmbed,
} from "ckeditor5";

import 'ckeditor5/ckeditor5.css'

const LICENSE_KEY = "GPL";

interface EditorProps {
  value: string
  onChange: (value: string) => void
  placeholder?: string
}

export default function Editor({ value, onChange, placeholder }: EditorProps) {
  return (
    <div className="w-full prose max-w-none">
      <CKEditor
        editor={ClassicEditor}
        config={{
          plugins: [
          Alignment,
          Autoformat,
          AutoImage,
          AutoLink,
          Autosave,
          Base64UploadAdapter,
          BlockQuote,
          Bold,
          CloudServices,
          Code,
          CodeBlock,
          Emoji,
          Essentials,
          FontBackgroundColor,
          FontColor,
          FontFamily,
          FontSize,
          GeneralHtmlSupport,
          Heading,
          Highlight,
          HorizontalLine,
          ImageBlock,
          ImageCaption,
          ImageInline,
          ImageInsertViaUrl,
          ImageStyle,
          ImageTextAlternative,
          ImageToolbar,
          ImageUpload,
          Indent,
          IndentBlock,
          Italic,
          Link,
          LinkImage,
          List,
          MediaEmbed,
          Mention,
          Paragraph,
          PasteFromMarkdownExperimental,
          PlainTableOutput,
          ShowBlocks,
          SourceEditing,
          Strikethrough,
          Subscript,
          Superscript,
          Table,
          TableCaption,
          TableToolbar,
          TextTransformation,
          Underline,
          ImageResize,
          TableCellProperties,
          TableProperties,
          TableColumnResize,
          TableCaption,
          HtmlEmbed,
          Style,
          AutoMediaEmbed,
        ],
          toolbar: [
             "undo",
            "redo",
            "htmlEmbed",
            "|",
            "showBlocks",
            "|",
            "sourceEditing",
            "|",
            "heading",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "subscript",
            "superscript",
            "code",
            "|",
            "emoji",
            "horizontalLine",
            "link",
            "uploadImage",
            "insertImageViaUrl",
            "mediaEmbed",
            "insertTable",
            "highlight",
            "blockQuote",
            "codeBlock",
            "|",
            "alignment",
            "|",
            "bulletedList",
            "numberedList",
            "outdent",
            "indent",
          ],
          placeholder: placeholder,
          licenseKey: LICENSE_KEY,
        }}
        data={value}
        onChange={(event, editor) => {
          const data = editor.getData()
          onChange(data)
        }}
      />
    </div>
  )
}
